<b>
Провести дисперсионный анализ для определения того, есть ли различия среднего роста среди взрослых футболистов, хоккеистов и штангистов. Даны значения роста в трех группах случайно выбранных спортсменов: Футболисты: 173, 175, 180, 178, 177, 185, 183, 182. Хоккеисты: 177, 179, 180, 188, 177, 172, 171, 184, 180. Штангисты: 172, 173, 169, 177, 166, 180, 178, 177, 172, 166, 170.
</b>

In [1]:
import numpy as np
from scipy import stats 

In [3]:
football_height = np.array([173, 175, 180, 178, 177, 185, 183, 182])
football_height

array([173, 175, 180, 178, 177, 185, 183, 182])

In [4]:
hockey_height = np.array([177, 179, 180, 188, 177, 172, 171, 184, 180])
hockey_height

array([177, 179, 180, 188, 177, 172, 171, 184, 180])

In [5]:
weightlifter_height = np.array([172, 173, 169, 177, 166, 180, 178, 177, 172, 166, 170])
weightlifter_height

array([172, 173, 169, 177, 166, 180, 178, 177, 172, 166, 170])

In [7]:
stats.f_oneway?

In [10]:
alfa=0.05

In [9]:
result = stats.f_oneway(football_height, hockey_height, weightlifter_height)
result

F_onewayResult(statistic=5.500053450812596, pvalue=0.010482206918698694)

In [14]:
if result.pvalue > alfa:
    print('Нет статистически значимой зависимости')
else:
    print('Есть статистически значимая зависимость')

Есть статистически значимая зависимость


<b>Прикрепить ссылку на курсовой проект на github. (см. выбор темы в ДЗ к Уроку 6)</b>

Своя задача.


была взята выборка из 10 BLDC моторов. у каждоо мотора есть 3 обмотки, замерил сопротивлением каждой обмотки и индуктивность каждой обмотки. Хочется на основе этих данных оценить, какой будет доверительный интервал. 
найти какое будет значение при помощи доверительного интервала. вероятность 95%.
Делаю предположение, что все распределено нормально.


In [15]:
import pandas as pd